experiment:
  enable_pretrain: True
  n_montecarlo: 100

  cluster_optimizer:
    name: "SGD"
    lr: 0.005
    momentum: 0.9
  
  cluster_scheduler:
    name: "StepLR"
    step_size: 100
    gamma: 0.1
  
  loss:
    name: "DEC"
    weights:
      dec: 1.0e-0
      reconst: 1.0e-0
      # regular: 1.0e-4
  
model:
  name: "DEC"
  cluster_only: False
  encode_only: False

  autoencoder:
    network: "MLP" #"CNN" # 
    hidden_dims: [500,500,2000]
    latent_dim: 10
    use_maxpool: False
    use_batchnorm: False
  