experiment:
  loss:
    name: "GJRD"
    weights:
      ddc1: 1.0e-0 #2.0e-2
      ddc2: 5.0e-2
      ddc3: 5.0e-2
      reconst: 1.0e-0

model:
  name: "DDC"
  encode_only: True

  autoencoder:
    network: "CNN" #"MLP" #  
    # input_dim: 1
    hidden_dims: [32,64]
    latent_dim: 100
    latent_activation: "Tanh"
    